### PR TITLE
let's enable vTLS 1.3

### PR DESCRIPTION
**Pull request by kinjelom**
Now, there is no way to enable TLS v1.3, let's enable TLS v1.3.

### CODE REVIEW

**Comment by maxmoehl** [comment]
Could you please explain your change? I don't see how this changes anything related to TLSv1.3.

**Comment by kinjelom** [comment]
I'm sorry, my mistake - TLS v1.3 probably doesn't work due to the OpenSSL version in the stemcell.

**Comment by maxmoehl** [comment]
It does work, but it is disabled by default. In our internal backlog we have a item to deprecate the individual `no-*` options in favour of exposing [ssl-min-ver](https://docs.haproxy.org/2.8/configuration.html#5.1-ssl-min-ver) and [ssl-max-ver](https://docs.haproxy.org/2.8/configuration.html#5.1-ssl-max-ver). We are currently using the raw blocks to set those but this should really be a feature of the release.

> ssl-max-ver
> The default value is "TLSv1.2".

So if you are interested, feel free to contribute a PR :)

<sub>PS: I have it on my list to look into your other PR, but I have a lot on the table right now :/</sub>

**Comment by kinjelom** [comment]
@maxmoehl tkank you, I'll check it later.

My config based on https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28recommended.29

ops:
```yaml
- type: replace
  path: /instance_groups/name=haproxy/jobs/name=haproxy/properties/ha_proxy/ssl_ciphers?
  value: "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305"
- type: replace
  path: /instance_groups/name=haproxy/jobs/name=haproxy/properties/ha_proxy/disable_tls_13?
  value: false
- type: replace
  path: /instance_groups/name=haproxy/jobs/name=haproxy/properties/ha_proxy/disable_tls_12?
  value: false
- type: replace
  path: /instance_groups/name=haproxy/jobs/name=haproxy/properties/ha_proxy/disable_tls_11?
  value: true
- type: replace
  path: /instance_groups/name=haproxy/jobs/name=haproxy/properties/ha_proxy/disable_tls_10?
  value: true
```

haproxy.config:
```
global
    ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
    ssl-default-bind-ciphers TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305
    ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
    ssl-default-server-ciphers TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305
```

and test:
```
curl --tlsv1.3 --verbose https://...
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.0 (IN), TLS header, Unknown (21):
* TLSv1.3 (IN), TLS alert, handshake failure (552):
* error:0A000410:SSL routines::sslv3 alert handshake failure
* Closing connection 0
curl: (35) error:0A000410:SSL routines::sslv3 alert handshake failure
```

**Comment by kinjelom** [comment]
> > ssl-min/max-ver
I can do it, please review and merge PR #652 first

**Pull request closed without merging**
