### PR TITLE
ci: auto-merge dependency PRs

### PR DESCRIPTION
**Pull request by maxmoehl**

### CODE REVIEW

**Comment by maxmoehl** [comment]
@domdom82 please approve this PR once the token is there.

**Comment by b1tamara** [comment]
@maxmoehl Do you want to change the CODEOWNERS file in another PR?

**Comment by maxmoehl** [comment]
> @maxmoehl Do you want to change the CODEOWNERS file in another PR?

Good point!

**Review by b1tamara — APPROVED** [review]
LGTM

**Pull request merged**
