### PR TITLE
Add haproxy release to bosh release version number and patched version

### PR DESCRIPTION
**Pull request by Mrizwanshaik**
Change versioning in shipit script according to the "Versioning Guide"
Add new pipeline in order to create a release based on previous stable haproxy version. Make sure that the autobump-dependencies is using the maintenance branch for the second pipeline.

### CODE REVIEW

**Comment by peanball** [comment]
I've reassigned to the approver group for review.

**Review by plowin — DISMISSED** [review]
lgtm! 
As this needs a rebase to current master, you could also add back the newline at in shipit to keep it a bit more clean.

**Comment by plowin** [comment]
Just noticed this seems to be included in https://github.com/cloudfoundry/haproxy-boshrelease/pull/398/files?
Please request the review only after the proposal is finalized

**Comment by plowin** [comment]
@Mrizwanshaik, please remove the merge commits and rebase your changes on top of master

**Review by plowin — APPROVED** [review]

**Pull request merged**
